Repository hoprnet/hopr-community, pull requests merged in 2022-08, with the labels that each got.

#159 Document DAPP_STANDARD.md
  DAPP_STANDARD.md
Labels: documentation

#160 add hopr-chess
  ADMIN_GUIDE.md
  README.md
  projects/hopr-chess/.gitignore
  projects/hopr-chess/README.md
  projects/hopr-chess/deploy.json
  projects/hopr-chess/package.json
  projects/hopr-chess/public/favicon.ico
  projects/hopr-chess/public/index.html
  projects/hopr-chess/public/logo192.png
  projects/hopr-chess/public/logo512.png
  projects/hopr-chess/public/manifest.json
  projects/hopr-chess/public/robots.txt
  projects/hopr-chess/src/App.css
  projects/hopr-chess/src/App.test.tsx
  projects/hopr-chess/src/App.tsx
  projects/hopr-chess/src/app/hooks.ts
  projects/hopr-chess/src/components/Chessboard/Chessboard.tsx
  projects/hopr-chess/src/components/WebSocketHandler/WebSocketHandler.tsx
  projects/hopr-chess/src/components/WebSocketHandler/useWebSocket.ts
  projects/hopr-chess/src/index.css
  projects/hopr-chess/src/index.tsx
  projects/hopr-chess/src/lib/url.ts
  projects/hopr-chess/src/lib/utils.ts
  projects/hopr-chess/src/logo.svg
  projects/hopr-chess/src/react-app-env.d.ts
  projects/hopr-chess/src/reportWebVitals.ts
  projects/hopr-chess/src/setupTests.ts
  projects/hopr-chess/src/state/slices/chessSlice/chessSlice.ts
  projects/hopr-chess/src/state/slices/peerSlice/peerAPI.ts
  projects/hopr-chess/src/state/slices/peerSlice/peerSlice.ts
  projects/hopr-chess/src/state/store.ts
  projects/hopr-chess/tsconfig.json
  projects/hopr-chess/yarn.lock
Labels: enhancement

#162 Fix chess and status-board http/https and api token usage
  .envrc
  .gitignore
  flake.lock
  flake.nix
  projects/hopr-chess/src/state/slices/peerSlice/peerSlice.ts
  projects/hopr-status-board/src/App.tsx
  projects/hopr-status-board/src/api.ts
  projects/hopr-status-board/src/useWebSocket.ts
  shell.nix
Labels: bug

#163 Fix incorrect comparison
  projects/hopr-status-board/src/App.tsx
Labels: bug

#164 hopr-chess: use state selector for security token everywhere
  projects/hopr-chess/src/lib/utils.ts
  projects/hopr-chess/src/state/slices/peerSlice/peerSlice.ts
Labels: bug
